import pygame
GRASS_PNG=pygame.image.load('grass.png')
FLAG_PNG=pygame.image.load('flag.png')
MINE_PNG=pygame.image.load('mine.png')
BACKGROUND_COLOR=(16,130,16)
NUM_OF_ROWS=25
NUM_OF_COLS=50
TILE_SIZE=20
NUM_OF_MINES=20
NUM_OF_BUSHES=20
WINDOW_WIDTH=TILE_SIZE*NUM_OF_COLS
WINDOW_HEIGHT=TILE_SIZE*NUM_OF_ROWS
COLOR_OF_GRID="pink"
PLAYER_SPEED=20
LOSE_MESSAGE = "You Lost!"
WIN_MESSAGE = "You Won!"